import type { PositioningArchetype } from "./types";

export const ARCHETYPE_SIGNALS: Record<PositioningArchetype, string[]> = {
  "frontend-specialist": [
    "react",
    "typescript",
    "next.js",
    "design systems",
    "accessibility",
    "wcag",
    "component architecture",
    "css",
    "html",
    "vue",
    "angular",
    "ui",
    "frontend",
    "front-end",
  ],
  "full-stack-builder": [
    "node",
    "api design",
    "architecture",
    "ci/cd",
    "postgres",
    "backend",
    "server-side",
    "rest api",
    "graphql",
    "database",
    "full-stack",
    "fullstack",
    "express",
    "trpc",
    "sqlite",
  ],
  "ai-product-engineer": [
    "ai",
    "llm",
    "mcp",
    "developer tooling",
    "automation",
    "retrieval",
    "workflow systems",
    "machine learning",
    "nlp",
    "embedding",
    "vector",
    "claude",
    "openai",
    "langchain",
    "agent",
    "rag",
  ],
  "performance-engineer": [
    "performance",
    "web workers",
    "d3",
    "visualization",
    "large datasets",
    "optimization",
    "core web vitals",
    "lighthouse",
    "canvas",
    "webgl",
    "data visualization",
    "real-time",
    "packet",
  ],
  "startup-generalist": [
    "ownership",
    "product thinking",
    "shipping",
    "startup",
    "cross-functional",
    "end-to-end",
    "product mindset",
    "lean",
    "generalist",
    "early stage",
  ],
};

export const UNIQUENESS_WEIGHTS: Record<string, number> = {
  MCP: 10,
  "agent-readable metadata": 10,
  "retrieval architecture": 9,
  "100k packet visualization": 9,
  "Web Workers": 8,
  D3: 7,
  LLM: 7,
  visualization: 6,
  AI: 6,
  "performance optimization": 6,
  "Next.js": 3,
  Accessibility: 5,
  automation: 5,
  React: 2,
  TypeScript: 2,
};

export const SUPPRESS_RULES: Record<PositioningArchetype, string[]> = {
  "frontend-specialist": [
    "Do not lead with backend or infrastructure claims.",
    "Do not describe the candidate as only a React developer — emphasize architecture and system-level thinking.",
  ],
  "full-stack-builder": [
    "Do not over-emphasize the UI layer at the expense of architecture.",
    "Do not describe the candidate as only a frontend developer.",
  ],
  "ai-product-engineer": [
    "Do not lead with generic React or TypeScript claims.",
    "Do not describe the candidate as only a frontend developer.",
    "Do not repeat common framework buzzwords without AI product context.",
  ],
  "performance-engineer": [
    "Do not lead with generic framework usage.",
    "Do not describe the candidate as only a React developer.",
    "Do not reduce performance work to frontend bundle optimization alone.",
  ],
  "startup-generalist": [
    "Do not present the candidate as a deep specialist in one narrow area.",
    "Do not lead with enterprise-scale or large-org framework experience.",
  ],
};

export const EMPHASIS_RULES: Record<PositioningArchetype, string[]> = {
  "frontend-specialist": [
    "Lead with component architecture and design system experience.",
    "Emphasize accessibility and user experience depth.",
    "Use React and TypeScript as supporting credibility, not the headline.",
  ],
  "full-stack-builder": [
    "Lead with end-to-end ownership and delivery.",
    "Emphasize API design and architecture decisions.",
    "Use frontend frameworks as supporting evidence of breadth.",
  ],
  "ai-product-engineer": [
    "Lead with AI-assisted workflow engineering.",
    "Lead with developer tooling and retrieval systems.",
    "Use React as supporting credibility, not the primary claim.",
  ],
  "performance-engineer": [
    "Lead with visualization and performance optimization at scale.",
    "Emphasize large-scale data rendering and Web Workers.",
    "Use frontend frameworks as supporting evidence.",
  ],
  "startup-generalist": [
    "Lead with product ownership and shipping velocity.",
    "Emphasize cross-functional collaboration and adaptability.",
    "Use technical depth as supporting credibility, not the entry point.",
  ],
};
