export type PhraseMap = { phrases: string[]; value: string };

export const COMPANY_TRAIT_SIGNALS: PhraseMap[] = [
  {
    phrases: [
      "ownership",
      "own your work",
      "take ownership",
      "owner mindset",
      "you own",
      "personal ownership",
      // German
      "eigenverantwortung",
      "eigenverantwortlich",
      "verantwortung übernehmen",
      "du verantwortest",
      "du übernimmst",
      "eigenständige verantwortung",
    ],
    value: "ownership mindset",
  },
  {
    phrases: [
      "autonomous",
      "self-directed",
      "independent",
      "autonomy",
      "self-starter",
      "self-managed",
      // German
      "selbstständig",
      "eigenständig",
      "unabhängig arbeiten",
      "selbstorganisiert",
      "autark",
    ],
    value: "autonomy",
  },
  {
    phrases: [
      "small team",
      "lean team",
      "startup",
      "early stage",
      "fast-growing",
      "seed stage",
      "series a",
      "series b",
      "fast-paced",
      "high-growth",
      // German
      "start-up",
      "wachsendes unternehmen",
      "wachstumsphase",
      "frühphase",
      "dynamisches umfeld",
      "schnelles wachstum",
      "agiles umfeld",
      "hochdynamisch",
    ],
    value: "startup adaptability",
  },
  {
    phrases: [
      "cross-functional",
      "cross functional",
      "collaborate across teams",
      "work with designers",
      "work with product",
      "multidisciplinary",
      // German
      "bereichsübergreifend",
      "fachübergreifend",
      "zusammenarbeit mit design",
      "zusammenarbeit mit produkt",
      "interdisziplinär",
      "teamübergreifend",
    ],
    value: "cross-functional collaboration",
  },
  {
    phrases: [
      "mentoring",
      "mentor developers",
      "coaching",
      "grow the team",
      "develop junior",
      "technical leadership",
      "lead engineers",
      "engineering mentor",
      // German
      "junior-entwickler fördern",
      "technische führung übernehmen",
      "entwickler begleiten",
      "wissenstransfer",
      "entwicklercoaching",
    ],
    value: "engineering leadership",
  },
  {
    phrases: [
      "long-term",
      "sustainable",
      "maintainability",
      "maintainable",
      "technical debt",
      "clean code",
      "code quality",
      "engineering excellence",
      // German
      "langfristig",
      "wartbarkeit",
      "technische schulden",
      "code-qualität",
      "sauberer code",
      "solide basis",
      "nachhaltige softwareentwicklung",
    ],
    value: "long-term engineering mindset",
  },
  {
    phrases: [
      "user-centric",
      "customer focus",
      "user experience",
      "product impact",
      "product mindset",
      "outcome-driven",
      "value for users",
      "customer success",
      // German
      "nutzerzentriert",
      "nutzerfokus",
      "kundenfokus",
      "nutzererfahrung",
      "nutzerorientiert",
      "produktorientiert",
      "nutzerbedürfnisse",
    ],
    value: "product mindset",
  },
  {
    phrases: [
      "core platform",
      "developer experience",
      "devex",
      "internal tools",
      "developer productivity",
      // German
      "entwicklerproduktivität",
      "interne tools",
      "plattformteam",
      "entwicklererfahrung",
      "tooling",
    ],
    value: "platform engineering",
  },
  {
    phrases: [
      "scale",
      "scalable",
      "high-traffic",
      "millions of users",
      "high availability",
      "distributed",
      "high performance",
      // German
      "skalierbar",
      "hoher traffic",
      "hochverfügbar",
      "millionen von nutzern",
      "hochlastig",
      "verteilte systeme",
    ],
    value: "scale-focused engineering",
  },
  {
    phrases: [
      "accessibility",
      "a11y",
      "wcag",
      "inclusive design",
      "screen reader",
      "keyboard navigation",
      // German
      "barrierefreiheit",
      "barrierefrei",
      "barrierefreies",
      "zugänglichkeit",
      "inklusive gestaltung",
      "wcag-konform",
      "screenreader",
    ],
    value: "accessibility focus",
  },
  {
    phrases: [
      "performance",
      "optimization",
      "core web vitals",
      "lighthouse",
      "rendering performance",
      "bundle size",
      // German
      "optimierung",
      "ladezeit",
      "rendering-performance",
      "bundle-größe",
      "laufzeitoptimierung",
    ],
    value: "performance engineering",
  },
  {
    phrases: [
      "collaborative culture",
      "great team culture",
      "open and inclusive",
      "diverse team",
      "supportive environment",
      "flat hierarchy",
      // German
      "teamkultur",
      "offene kultur",
      "flache hierarchien",
      "unterstützendes umfeld",
      "diverse teams",
      "inklusive kultur",
      "wertschätzende zusammenarbeit",
    ],
    value: "collaborative culture",
  },
];

export const ENGINEERING_CULTURE_SIGNALS: PhraseMap[] = [
  {
    phrases: [
      "ci/cd",
      "continuous integration",
      "continuous deployment",
      "github actions",
      "jenkins",
      "pipelines",
      // German
      "kontinuierliche integration",
      "kontinuierliche auslieferung",
      "deployment-pipeline",
      "automatisierte pipelines",
      "build-pipeline",
    ],
    value: "engineering maturity (CI/CD culture)",
  },
  {
    phrases: [
      "code review",
      "pull request",
      "pr process",
      "pair programming",
      // German
      "code-review",
      "code reviews",
      "pull-request-prozess",
      "pair-programming",
    ],
    value: "collaborative code quality practices",
  },
  {
    phrases: [
      "tdd",
      "test-driven",
      "testing culture",
      "well-tested",
      "test coverage",
      "automated testing",
      // German
      "testgetriebene entwicklung",
      "testabdeckung",
      "automatisierte tests",
      "qualitätssicherung durch tests",
    ],
    value: "test-first engineering culture",
  },
  {
    phrases: [
      "microservices",
      "service-oriented",
      "event-driven",
      "event sourcing",
      // German
      "ereignisgesteuert",
      "serviceorientiert",
    ],
    value: "distributed systems mindset",
  },
  {
    phrases: [
      "documentation",
      "design docs",
      "rfcs",
      "architectural decision",
      "runbooks",
      // German
      "dokumentation",
      "technische dokumentation",
      "architekturentscheidungen",
      "designdokumente",
    ],
    value: "documentation culture",
  },
  {
    phrases: [
      "open source",
      "contribute to oss",
      "inner source",
      "open-source",
      // German
      "quelloffen",
      "open-source-projekte",
      "open-source-beiträge",
    ],
    value: "open source culture",
  },
  {
    phrases: [
      "agile",
      "scrum",
      "sprint",
      "kanban",
      "lean methodology",
      // German
      "agil",
      "agiles vorgehen",
      "agile methoden",
    ],
    value: "agile delivery process",
  },
  {
    phrases: [
      "observability",
      "monitoring",
      "logging",
      "tracing",
      "alerting",
      "on-call",
      "sre",
      "site reliability",
      // German
      "überwachung",
      "protokollierung",
      "incident response",
      "betriebsstabilität",
    ],
    value: "production excellence mindset",
  },
];

export const INFERRED_PRIORITY_SIGNALS: PhraseMap[] = [
  {
    phrases: [
      "frontend",
      "front-end",
      "ui development",
      "user interface",
      "react developer",
      "next.js",
      "vue developer",
      "web components",
      // German
      "frontend-entwicklung",
      "front-end-entwicklung",
      "ui-entwicklung",
      "benutzeroberfläche",
      "react-entwickler",
      "webentwicklung",
      "webanwendungen",
      "komponentenentwicklung",
    ],
    value: "frontend craft",
  },
  {
    phrases: [
      "backend",
      "back-end",
      "api development",
      "server-side",
      "node.js developer",
      "python developer",
      "microservice",
      "rest api",
      "graphql backend",
      // German
      "backend-entwicklung",
      "back-end-entwicklung",
      "api-entwicklung",
      "serverseitig",
      "microservices-entwicklung",
    ],
    value: "backend engineering",
  },
  {
    phrases: [
      "full-stack",
      "fullstack",
      "end-to-end engineering",
      "across the stack",
      "both frontend and backend",
      // German
      "vollständiger technologie-stack",
      "vom backend bis frontend",
      "gesamter stack",
      "end-to-end-entwicklung",
    ],
    value: "full-stack delivery",
  },
  {
    phrases: [
      "machine learning",
      "ml engineer",
      "ai engineer",
      "data science",
      "deep learning",
      "llm",
      "large language model",
      "nlp",
      "computer vision",
      // German
      "ki-entwicklung",
      "ki-ingenieur",
      "maschinelles lernen",
      "datenwissenschaft",
      "sprachmodelle",
      "llm-integration",
      "künstliche intelligenz",
    ],
    value: "AI/ML engineering",
  },
  {
    phrases: [
      "mobile",
      "ios developer",
      "android developer",
      "react native",
      "flutter",
      "native app",
      // German
      "mobile entwicklung",
      "ios-entwicklung",
      "android-entwicklung",
      "native app-entwicklung",
    ],
    value: "mobile engineering",
  },
  {
    phrases: [
      "infrastructure",
      "devops",
      "sre",
      "platform engineer",
      "kubernetes",
      "docker",
      "terraform",
      "cloud architect",
      // German
      "infrastruktur",
      "devops-ingenieur",
      "plattformingenieur",
      "cloud-architekt",
      "infrastrukturentwicklung",
    ],
    value: "infrastructure and DevOps",
  },
  {
    phrases: [
      "lead engineer",
      "tech lead",
      "senior engineer",
      "principal engineer",
      "staff engineer",
      "engineering manager",
      "head of engineering",
      // German
      "leitender ingenieur",
      "leitender entwickler",
      "technischer leiter",
      "senior-ingenieur",
      "abteilungsleiter",
      "lead engineer",
    ],
    value: "technical leadership",
  },
  {
    phrases: [
      "product engineer",
      "growth engineering",
      "user acquisition",
      "conversion",
      "a/b testing",
      "retention",
      // German
      "produktingenieur",
      "wachstums-engineering",
      "a/b-tests",
      "conversion-optimierung",
      "nutzerakquise",
    ],
    value: "product-focused delivery",
  },
];
